version: "3"

services:
  database:
    container_name: taskly-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - taskly_network
    restart: always

  phpmyadmin:
    container_name: taskly-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
    ports:
      - 5050:80
    networks:
      - taskly_network
    restart: always

  api:
    container_name: taskly-api
    image: taskly-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    networks:
      - taskly_network
    restart: always

  client:
    container_name: taskly-client
    image: taskly-client
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    depends_on:
      - api
    ports:
      - 4200:4200
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - taskly_network
    restart: always

networks:
  taskly_network:
    name: taskly_network

volumes:
  database:
