spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskly
    username: fluchten
    password: 19

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liDmXLJJO5DZf7A5
            client-secret: fb0b8875b43782496908bdcccf38d75ca28a4bae
